name: Push Release

on:
  push:
    branches: [ main ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - name: 检查main分支
        uses: actions/checkout@main

      - name: 设置Node.js
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: 打包编译
        run: npm run build

      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: /package.json
          property: version

      - name: 发布NPM包
        run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

      - name: 建立GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.value}}
          release_name: v${{steps.version.outputs.value}}
          draft: false
          prerelease: false